### ISSUE TITLE
Newsletter boiler-plate

### ISSUE THREAD

**Issue by kpearson** [fullstackla/newsletter#3]
js.la is a great example to build from.

Follow this link to an example of the js.la newsletter. https://share.polymail.io/v1/z/s/cSiEpRLfYyQwItEZ/jUG0FCRXovSDOWRXvA42mP9F1z9RqPkuBQ2BQmLPcW45IuDhPh8riyd0NjONc4EJHKXJUfBmj-1p3uX_xL2sCkbWCrW0gklM55o=

**Comment by jaimemendozadev** [comment]
Hey @kpearson, thanks sooooo much for the invite! You know for sure I'll help if I can! I'll get started on FSLA stuff either tomorrow or Monday. Hopefully soon.

**Comment by machikoyasuda** [comment]
Closing bc September is over.
